name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/dev.txt
      - name: Run tests
        run: coverage run --branch --source=denoising_inpainting_lbp/ --omit=**/__init__.py -m pytest
      - name: Show coverage report
        run: coverage report
      - name: Run linter
        run: pylint --disable=E1101 denoising_inpainting_lbp/
      - name: Run type checker
        run: mypy --ignore-missing-imports denoising_inpainting_lbp/ 
