name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: coverage run --branch --source=denoising_inpainting/ --omit=**/__init__.py -m pytest
      - name: Show coverage report
        run: coverage report
      - name: Run linter
        run: flake8 --exclude **/__init__.py --max-complexity 10 denoising_inpainting/ 
      - name: Run type checker
        run: mypy --ignore-missing-imports denoising_inpainting/ 
